using System.Collections.Generic;
using UnityEngine;

public class PopupQuest : MonoBehaviour
{
    [SerializeField] private NavSchedule navSchedule;
    [SerializeField] private List<SlotQuestSelect> QuestSlots = new();

    private void OnEnable()
    {
        for (int i = 0; i < QuestSlots.Count; i++)
        {
            QuestSlots[i].SetQSlot(DataManager.Instance.GetData<QuestData>(nameof(QuestData), navSchedule.QuestSlotIdx[i]));
        }
    }

    public void OnSelectSlot(int listIdx)
    {
        GameManager.Instance.OnQuestSelectEvent(listIdx);
        gameObject.SetActive(false);
    }
}